// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrziY4Px3Aj5u_j_dbube5KCbuiQFVLMA',
    appId: '1:443596751182:web:fdc1e6c22e1c65b7cb1e1f',
    messagingSenderId: '443596751182',
    projectId: 'instantgram-jahidcs',
    authDomain: 'instantgram-jahidcs.firebaseapp.com',
    storageBucket: 'instantgram-jahidcs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_XupBIFfPnDexRbRC4LfyvyXBUHmmWY',
    appId: '1:443596751182:android:85ca801b462f51cdcb1e1f',
    messagingSenderId: '443596751182',
    projectId: 'instantgram-jahidcs',
    storageBucket: 'instantgram-jahidcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2mM68ZEVpQjfRNlpkeoqErDw8JG6_SiI',
    appId: '1:443596751182:ios:e033d0486dd5e63bcb1e1f',
    messagingSenderId: '443596751182',
    projectId: 'instantgram-jahidcs',
    storageBucket: 'instantgram-jahidcs.appspot.com',
    iosClientId: '443596751182-o14dk5g2jpppd1ts06ts63jn73ifu86f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2mM68ZEVpQjfRNlpkeoqErDw8JG6_SiI',
    appId: '1:443596751182:ios:e033d0486dd5e63bcb1e1f',
    messagingSenderId: '443596751182',
    projectId: 'instantgram-jahidcs',
    storageBucket: 'instantgram-jahidcs.appspot.com',
    iosClientId: '443596751182-o14dk5g2jpppd1ts06ts63jn73ifu86f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram',
  );
}
